[package]
name = "file_integrity_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "file_integrity_lib"
path = "src/lib.rs" 

[dependencies]
md-5 = "0.10.5"
chrono = "0.4.26"
serde = { version = "1.0.179", features = ["derive"] }
serde_json = "1.0.103"
my_logger = "0.1.4"